import argparse
import hashlib
import hmac
import json
import os
import secrets
from datetime import datetime, timezone
from typing import Dict, List


def canonical_json(data: Dict[str, object]) -> str:
    return json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def ensure_signing_key(path: str) -> str:
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            key = f.read().strip()
        if key:
            return key
    os.makedirs(os.path.dirname(path), exist_ok=True)
    key = secrets.token_urlsafe(48)
    with open(path, "w", encoding="utf-8") as f:
        f.write(key)
    return key


def secret_parts(secret: str) -> List[str]:
    out: List[str] = []
    idx = 0
    while idx < len(secret):
        out.append(secret[idx: idx + 8])
        idx += 8
    return out


def write_embed_module(path: str, payload: Dict[str, object], signature: str, parts: List[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload_json = json.dumps(payload, indent=2, ensure_ascii=False)
    parts_json = json.dumps(parts, ensure_ascii=False)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/generate_license.py. Do not edit manually.\n")
        f.write(f"LICENSE_PAYLOAD = {payload_json}\n")
        f.write(f"LICENSE_SIGNATURE = \"{signature}\"\n")
        f.write(f"LICENSE_SECRET_PARTS = {parts_json}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate signed embedded license for School Election App.")
    parser.add_argument("--school-name", required=True)
    parser.add_argument("--valid-days", type=int, required=True)
    parser.add_argument("--licensee-id", required=True)
    parser.add_argument("--developer-name", default="EmpowerID")
    parser.add_argument("--developer-contact", default="")
    parser.add_argument("--key-path", default="tools/.license-signing-key")
    parser.add_argument("--out", default="build/license_embed.py")
    args = parser.parse_args()

    if args.valid_days <= 0:
        raise ValueError("--valid-days must be > 0")

    key = ensure_signing_key(args.key_path)

    payload: Dict[str, object] = {
        "license_id": args.licensee_id.strip(),
        "school_name": args.school_name.strip(),
        "valid_days": int(args.valid_days),
        "issued_at": utc_now_iso(),
        "developer_name": args.developer_name.strip(),
        "developer_contact": args.developer_contact.strip(),
    }
    canonical = canonical_json(payload)
    signature = hmac.new(key.encode("utf-8"), canonical.encode("utf-8"), hashlib.sha256).hexdigest()
    write_embed_module(args.out, payload, signature, secret_parts(key))
    print(f"Generated signed license module at: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

